apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "fullname" . }}
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ci-backup
            image: quay.io/samsung-cnct/gitlab-operator
            args:
            - /bin/sh
            - -c
            - gitlab-operator help
          restartPolicy: OnFailure